# This dictionary maps raw seniority labels from the dataset to broader, 
# standardized categories.
seniority_mapping = {
    'non_manager': 'Non-Managerial Position',
    'manager': 'Managerial Position',
    'director': 'Managerial Position',
    'head': 'Managerial Position',
    'vice_president': 'Executive Position',
    'c_level': 'Executive Position',
    'partner': 'Executive Position',
    'president': 'Executive Position',
}


# This dictionary maps specific O*NET job families into broader, 
# standardized job field categories.
job_fields_mapping = {
    'office and administrative support' : 'Business and Administration',
    'architecture and engineering': 'Engineering and Construction',
    'computer and mathematical' : 'Technology',
    'sales and related': 'Business and Administration',    
    'installation, maintenance, and repair': 'Facilities Management and Services',
    'business and financial operations' : 'Business and Administration',
    'production': 'Manufacturing',
    'life, physical, and social science' : 'Science and Research',
    'management': 'Business and Administration',
    'community and social service' : 'Public Service',
    'transportation and material moving': 'Transportation and Logistics',
    'healthcare practitioners and technical' : 'Healthcare',
    'personal care and service': 'Healthcare',
    'educational instruction and library' : 'Education',
    'construction and extraction': 'Engineering and Construction',
    'arts, design, entertainment, sports, and media': 'Multimedia and Sports',
    'food preparation and serving related' : 'Facilities Management and Services',
    'protective service': 'Government and Public Safety',
    'military specific' : 'Government and Public Safety',
    'legal' : 'Legal Services',
    'healthcare support': 'Healthcare',
    'farming, fishing, and forestry': 'Agriculture and Natural Resources',
    'building and grounds cleaning and maintenance': 'Facilities Management and Services', 
    'nan' : 'Others'
}

# This dictionary maps raw and multilingual representations of contract types 
# into standardized employment categories.
contract_types_mapping = {
    # Full Time
    'full time': 'Full Time',
    'tempo integral': 'Full Time',
    'vollzeit': 'Full Time',
    'fuldtid': 'Full Time',
    'temps plein': 'Full Time',
    'pe_ny_etat': 'Full Time',  # likely "permanent employment" in Danish/Norwegian

    # Part Time
    'part time': 'Part Time',
    'deltid': 'Part Time',
    'temps partiel': 'Part Time',

    # Internship/Trainee
    'internship': 'Internship/Trainee',
    'intern': 'Internship/Trainee',
    'trainee': 'Internship/Trainee',
    'practitioner': 'Internship/Trainee',
    'summer': 'Internship/Trainee',

    # Remote/Flexible Work
    'remote': 'Remote/Flexible',
    'fully remote': 'Remote/Flexible',
    'work from home': 'Remote/Flexible',
    'trabalho remoto': 'Remote/Flexible',
    'teletrabajo': 'Remote/Flexible',

    # Contract/Temporary
    'contract': 'Contract/Temporary',
    'contractor': 'Contract/Temporary',
    'temporary': 'Contract/Temporary',
    'freelance': 'Contract/Temporary',
    'tempo indeterminato': 'Contract/Temporary',

    # Shifts/Schedule Types
    'day shift': 'Shift Work',
    'night shift': 'Shift Work',
    'short term': 'Short Term',
    'long term': 'Long Term',
    'day time': 'Day Time',
    'm f': 'Monday-Friday',

    # Industry/Role Specific
    'onsite': 'On-site',
    'hybrid': 'Hybrid',
    'all levels': 'All Levels',
    'commission': 'Commission',
    'festanstellung': 'Permanent',
    'vaste aanstelling': 'Permanent',
    'permanent': 'Permanent',
    'nuit': 'Night',
    'full or part time': 'Full or Part Time',
    'm/w': 'Male/Female'
}

# This dictionary is used to group raw keyword entries from the `Keywords` column
# into broader, standardized skill categories. 
keywords_skills_mapping = {

    # Programming Languages
    'c++': 'Programming Languages',
    'python': 'Programming Languages',
    'c#': 'Programming Languages',
    'java': 'Programming Languages',
    'kotlin': 'Programming Languages',
    'javascript': 'Programming Languages',
    'php': 'Programming Languages',
    'ruby': 'Programming Languages',
    'abap': 'Programming Languages',
    'go': 'Programming Languages',
    'typescript': 'Programming Languages',
    'perl': 'Programming Languages',
    'dart': 'Programming Languages',
    'c': 'Programming Languages',
    'cobol': 'Programming Languages',
    'objective-c': 'Programming Languages',
    'scala': 'Programming Languages',
    'solidity': 'Programming Languages',
    'visual basic .net': 'Programming Languages', 
    'json': 'Programming Languages',
    'xslt': 'Programming Languages', 
    
    # Frameworks & Libraries
    '.net': 'Frameworks & Libraries',
    'angular': 'Frameworks & Libraries',
    'django': 'Frameworks & Libraries',
    'node.js': 'Frameworks & Libraries',
    'angularjs': 'Frameworks & Libraries',
    'react': 'Frameworks & Libraries',
    'spring framework': 'Frameworks & Libraries',
    'spring boot': 'Frameworks & Libraries',
    'flask': 'Frameworks & Libraries',
    'jquery': 'Frameworks & Libraries',
    'vue.js': 'Frameworks & Libraries',
    'laravel': 'Frameworks & Libraries',
    'gatsby': 'Frameworks & Libraries',
    'graphql': 'Frameworks & Libraries',
    'remix': 'Frameworks & Libraries',
    'primefaces': 'Frameworks & Libraries',
    'blazor': 'Frameworks & Libraries',
    'rxjs': 'Frameworks & Libraries',
    'svelte': 'Frameworks & Libraries',
    'drupal': 'Frameworks & Libraries',
    'jekyll': 'Frameworks & Libraries',
    'bootstrap': 'Frameworks & Libraries',
    'ext js': 'Frameworks & Libraries',
    'next.js': 'Frameworks & Libraries',
    'mui': 'Frameworks & Libraries',
    'primeng': 'Frameworks & Libraries',
    'scikit-learn': 'Frameworks & Libraries',
    'pytorch': 'Frameworks & Libraries',
    'tensorflow': 'Frameworks & Libraries',
    'ionic': 'Frameworks & Libraries',
    'j2ee': 'Frameworks & Libraries',
    'junit': 'Frameworks & Libraries',
    'nunit': 'Frameworks & Libraries',
    'redux': 'Frameworks & Libraries',
    'nette framework': 'Frameworks & Libraries',
    'front-end': 'Frameworks & Libraries',
    'back-end': 'Frameworks & Libraries',
    'ui/ux': 'Frameworks & Libraries',
    'bem': 'Frameworks & Libraries',
    'websocket': 'Frameworks & Libraries',
    'webrtc': 'Frameworks & Libraries',
    'openid connect': 'Frameworks & Libraries',
    'grpc': 'Frameworks & Libraries',
    'pwa': 'Frameworks & Libraries',
    'mobx': 'Frameworks & Libraries',
    'vue storefront': 'Frameworks & Libraries',
    'jetpack': 'Frameworks & Libraries',
    'ethers': 'Frameworks & Libraries',
    'microsoft.net': 'Frameworks & Libraries',
    'netcore': 'Frameworks & Libraries',
    
    # Tools & Platforms
    'github': 'Tools & Platforms',
    'gitlab': 'Tools & Platforms',
    'jenkins': 'Tools & Platforms',
    'docker': 'Tools & Platforms',
    'kubernetes': 'Tools & Platforms',
    'ansible': 'Tools & Platforms',
    'postman': 'Tools & Platforms',
    'selenium': 'Tools & Platforms',
    'appium': 'Tools & Platforms',
    'gradle': 'Tools & Platforms',
    'gerrit': 'Tools & Platforms',
    'ranorex': 'Tools & Platforms',
    'splunk': 'Tools & Platforms',
    'matlab': 'Tools & Platforms',
    'minitab': 'Tools & Platforms',
    'autocad': 'Tools & Platforms',
    'arduino': 'Tools & Platforms',
    'stata': 'Tools & Platforms',
    'labview': 'Tools & Platforms',
    'simulink': 'Tools & Platforms',
    'ansys': 'Tools & Platforms',
    'catia': 'Tools & Platforms',
    'ptc creo': 'Tools & Platforms',
    'android studio': 'Tools & Platforms',
    'visual studio code': 'Tools & Platforms',
    'eclipse ide': 'Tools & Platforms',
    'microsoft visual studio': 'Tools & Platforms',
    'autodesk eagle': 'Tools & Platforms',
    'autodesk revit': 'Tools & Platforms',
    'corel': 'Tools & Platforms',
    'dreamweaver': 'Tools & Platforms',
    'paintshop pro': 'Tools & Platforms',
    'sourcetree': 'Tools & Platforms',
    'webstorm': 'Tools & Platforms',
    'robot framework': 'Tools & Platforms',
    'jupyter': 'Tools and Platforms',
    'vite': 'Tools and Platforms',
    'unity3d': 'Tools and Platforms',
    'axure': 'Tools and Platforms',
    'artifactory': 'Tools and Platforms',
    'sonarqube': 'Tools and Platforms',
    'avid pro tools': 'Tools and Platforms',
    'automic': 'Tools and Platforms',
    'outsystems': 'Tools and Platforms',
    'windchill': 'Tools and Platforms',
    'thingworx': 'Tools and Platforms',
    'articulate 360': 'Tools and Platforms',
    'wonderlic': 'Tools and Platforms',
    'weights & biases': 'Tools and Platforms',
    '1password': 'Tools and Platforms',
    'keyless': 'Tools and Platforms',
    
    # Cloud Services
    'microsoft azure': 'Cloud Services',
    'azure devops': 'Cloud Services',
    'google cloud': 'Cloud Services',
    'amazon web services': 'Cloud Services',
    'google cloud platform': 'Cloud Services',
    'oracle cloud': 'Cloud Services',
    'azure stream analytics': 'Cloud Services',
    'azure kubernetes service': 'Cloud Services',
    'azure pipelines': 'Cloud Services',
    'azure synapse analytics': 'Cloud Services',
    'azure sql': 'Cloud Services',
    'azure artifacts': 'Cloud Services',
    'azure boards': 'Cloud Services',
    'azure monitor': 'Cloud Services',
    'google kubernetes engine': 'Cloud Services',
    'aws iot': 'Cloud Services',
    'aws lambda': 'Cloud Services',
    'amazon ecs': 'Cloud Services',
    'amazon rds': 'Cloud Services',
    'google workspace': 'Cloud Services',
    'azure databricks': 'Cloud Services',
    'databricks': 'Cloud Services',
    'cloudera': 'Cloud Services',
    'microsoft 365': 'Cloud Services',
    'office 365': 'Cloud Services',
    'microsoft power bi': 'Cloud Services',
    'microsoft power apps': 'Cloud Services',
    'microsoft power automate': 'Cloud Services',
    'microsoft sharepoint': 'Cloud Services',
    'microsoft sharepoint online': 'Cloud Services',
    'microsoft active directory': 'Cloud Services',
    'microsoft system center': 'Cloud Services',
    'google sheets': 'Cloud Services',
    'google drive': 'Cloud Services',
    'zoom': 'Cloud Services',
    'skype': 'Cloud Services',
    
    # Databases
    'mysql': 'Databases',
    'mongodb': 'Databases',
    'postgresql': 'Databases',
    'oracle database': 'Databases',
    'microsoft sql server': 'Databases',
    'nosql': 'Databases',
    'sqlite': 'Databases',
    'couchbase': 'Databases',
    'redis': 'Databases',
    'netezza': 'Databases',
    'teradata analytics platform': 'Databases',
    'sybase': 'Databases',
    'mariadb': 'Databases',
    'snowflake': 'Databases',
    'hadoop': 'Databases',
    'apache hadoop': 'Databases',
    'lucene': 'Databases',
    'solr': 'Databases',
    'elasticsearch': 'Databases',
    'opensearch': 'Databases',
    'oracle exadata': 'Databases',
    
    # Operating Systems
    'linux': 'Operating Systems',
    'windows server': 'Operating Systems',
    'macos': 'Operating Systems',
    'ubuntu': 'Operating Systems',
    'ibm aix': 'Operating Systems',
    'debian': 'Operating Systems',
    'unix': 'Operating Systems',
    'windows 11': 'Operating Systems',
    'suse': 'Operating Systems',
    'vmware esxi': 'Operating Systems',
    'cuda': 'Operating Systems',

    
    # DevOps & CI/CD
    'continuous deployment': 'DevOps & CI/CD',
    'git': 'DevOps & CI/CD',
    'gitlab ci': 'DevOps & CI/CD',
    'circleci': 'DevOps & CI/CD',
    'jenkins': 'DevOps & CI/CD',  
    'docker': 'DevOps & CI/CD',  
    'kubernetes': 'DevOps & CI/CD',  
    'ansible': 'DevOps & CI/CD',  
    'gradle': 'DevOps & CI/CD',
    'rabbitmq': 'DevOps & CI/CD',
    'apache tomcat': 'DevOps & CI/CD',
    'apache jmeter': 'DevOps & CI/CD',
    'apache airflow': 'DevOps & CI/CD',
    'mlflow': 'DevOps & CI/CD',
    'dbt': 'DevOps & CI/CD',
    'fivetran': 'DevOps & CI/CD',
    'iis': 'DevOps & CI/CD',
    'nginx': 'DevOps & CI/CD',
    'jboss': 'DevOps & CI/CD',
    'webmethods': 'DevOps & CI/CD',
    'boomi': 'DevOps & CI/CD',
    'mulesoft anypoint platform': 'DevOps & CI/CD',
    'dataweave': 'DevOps & CI/CD',  
    
    # ERP & Business Software
    'sap': 'ERP & Business Software',
    'sap successfactors': 'ERP & Business Software',
    'sap s/4hana': 'ERP & Business Software',
    'sap hana': 'ERP & Business Software',
    'sap erp': 'ERP & Business Software',
    'sap abap': 'ERP & Business Software',
    'sap financial accounting': 'ERP & Business Software',
    'sap sales': 'ERP & Business Software',
    'sap controlling': 'ERP & Business Software',
    'sap fiori': 'ERP & Business Software',
    'sap crm': 'ERP & Business Software',
    'sap analytics cloud': 'ERP & Business Software',
    'sap bw/4hana': 'ERP & Business Software',
    'sap netweaver': 'ERP & Business Software',
    'sap strategic enterprise management': 'ERP & Business Software',
    'sap materials management': 'ERP & Business Software',
    'sap treasury and risk management': 'ERP & Business Software',
    'sap quality management': 'ERP & Business Software',
    'sap solution manager': 'ERP & Business Software',
    'sap lumira': 'ERP & Business Software',
    'sap data migration': 'ERP & Business Software',
    'sap master data governance': 'ERP & Business Software',
    'sap cloud platform': 'ERP & Business Software',
    'sap grc': 'ERP & Business Software',
    'sap enable now': 'ERP & Business Software',
    'sap business warehouse': 'ERP & Business Software',
    'sap warehouse management': 'ERP & Business Software',
    'sap sales and distribution': 'ERP & Business Software',
    'sap ariba': 'ERP & Business Software',
    'sap hybris': 'ERP & Business Software',
    'oracle': 'ERP & Business Software',
    'netsuite': 'ERP & Business Software',
    'microsoft dynamics': 'ERP & Business Software',
    'microsoft dynamics 365': 'ERP & Business Software',
    'microsoft dynamics crm': 'ERP & Business Software',
    'workday payroll': 'ERP & Business Software',
    'adp': 'ERP & Business Software',
    'ukg': 'ERP & Business Software',
    'kronos': 'ERP & Business Software',
    'coupa': 'ERP & Business Software',
    'celonis': 'ERP & Business Software',
    'alteryx': 'ERP & Business Software',
    'talend': 'ERP & Business Software',
    'informatica': 'ERP & Business Software',
    'hris': 'ERP & Business Software',
    'concur': 'ERP & Business Software',
    'servicenow': 'ERP & Business Software',
    'bmc remedy': 'ERP & Business Software',
    'microsoft excel': 'ERP & Business Software',
    'microsoft word': 'ERP & Business Software',
    'microsoft powerpoint': 'ERP & Business Software',
    'microsoft outlook': 'ERP & Business Software',
    'jda': 'ERP & Business Software',
    'blue yonder': 'ERP & Business Software',
    'kinaxis': 'ERP & Business Software',
    'personio': 'ERP & Business Software',
    'oracle enterprise manager': 'ERP & Business Software',
    'quickbooks': 'ERP & Business Software',
    'hyperion': 'ERP & Business Software',
    'blackline': 'ERP & Business Software',
    'zuora': 'ERP & Business Software',
    'centricity': 'ERP & Business Software',
    'planisware': 'ERP & Business Software',
    'edenred': 'ERP & Business Software',
    'timesheets': 'ERP & Business Software',
    
    # CRM
    'salesforce': 'CRM',
    'salesforce commerce cloud': 'CRM',
    'salesforce marketing cloud': 'CRM',
    'hubspot': 'CRM',
    'gainsight': 'CRM',
    'customer success': 'CRM',
    'churnzero': 'CRM',
    'planhat': 'CRM',
    'outreach': 'CRM',
    'insightsquared': 'CRM',
    
    # CMS & Web Platforms
    'wordpress': 'CMS & Web Platforms',
    'drupal': 'CMS & Web Platforms',
    'sitecore': 'CMS & Web Platforms',
    'contentful': 'CMS & Web Platforms',
    'contentstack': 'CMS & Web Platforms',
    'shopify': 'CMS & Web Platforms',
    'webflow': 'CMS & Web Platforms',
    'ecommerce': 'CMS & Web Platforms',
    'e-commerce': 'CMS & Web Platforms',
    'demandware': 'CMS & Web Platforms',
    'commercetools': 'CMS & Web Platforms',
    'salsify': 'CMS & Web Platforms',
    'covisint': 'CMS & Web Platforms',
    'hydrogen': 'CMS & Web Platforms',
    
    # Marketing & Social Media Tools
    'google analytics': 'Marketing & Social Media Tools',
    'google ads': 'Marketing & Social Media Tools',
    'google adwords': 'Marketing & Social Media Tools',
    'facebook ads': 'Marketing & Social Media Tools',
    'linkedin': 'Marketing & Social Media Tools',
    'agorapulse': 'Marketing & Social Media Tools',
    'hootsuite': 'Marketing & Social Media Tools',
    'semrush': 'Marketing & Social Media Tools',
    'ahrefs': 'Marketing & Social Media Tools',
    'marketo': 'Marketing & Social Media Tools',
    'hubspot': 'Marketing & Social Media Tools',  
    'pinterest': 'Marketing & Social Media Tools',
    'youtube': 'Marketing & Social Media Tools',
    'optimizely': 'Marketing & Social Media Tools',
    'google optimize': 'Marketing & Social Media Tools',
    'google my business': 'Marketing & Social Media Tools',
    'linkedin sales navigator': 'Marketing & Social Media Tools',
    'zoominfo': 'Marketing & Social Media Tools',
    'outreach.io': 'Marketing & Social Media Tools',
    'demandbase': 'Marketing & Social Media Tools',
    'sendoso': 'Marketing & Social Media Tools',
    'account based marketing': 'Marketing & Social Media Tools',
    'demand generation': 'Marketing & Social Media Tools',
    'content marketing': 'Marketing & Social Media Tools',
    'seo': 'Marketing & Social Media Tools',
    'social media': 'Marketing & Social Media Tools',
    'branding': 'Marketing & Social Media Tools',
    'marketing campaigns': 'Marketing & Social Media Tools',
    'copywriter': 'Marketing & Social Media Tools',
    'martech': 'Marketing & Social Media Tools',
    'microsoft advertising': 'Marketing & Social Media Tools',
    'centro': 'Marketing & Social Media Tools',
    'borlabs cookie': 'Marketing & Social Media Tools',
    'leadfeeder': 'Marketing & Social Media Tools',
    'provenexpert': 'Marketing & Social Media Tools',
    
    # Design Tools
    'figma': 'Design Tools',
    'adobe creative suite': 'Design Tools',
    'adobe photoshop': 'Design Tools',
    'adobe indesign': 'Design Tools',
    'adobe illustrator': 'Design Tools',
    'adobe xd': 'Design Tools',
    'adobe after effects': 'Design Tools',
    'adobe acrobat dc': 'Design Tools',
    'adobe premiere pro': 'Design Tools',
    'adobe captivate': 'Design Tools',
    'adobe framemaker': 'Design Tools',
    'canva': 'Design Tools',
    'sketch': 'Design Tools',
    'cropping': 'Design Tools',
    'post-production': 'Design Tools',
    'metadata': 'Design Tools',  
    
    
    # Project Management
    'jira': 'Project Management',
    'trello': 'Project Management',
    'asana': 'Project Management',
    'smartsheet': 'Project Management',
    'microsoft teams': 'Project Management',
    'conceptboard': 'Project Management',
    'cutover': 'Project Management',
    'kanban': 'Project Management',
    'scrum': 'Project Management',
    'atlassian': 'Project Management',
    'atlassian jira': 'Project Management',
    'atlassian bitbucket': 'Project Management',
    'swimlane': 'Project Management',
    'bizzabo': 'Project Management',
    'hopin': 'Project Management',
    'kahoot': 'Project Management',
    'buildout': 'Project Management',
    
    
    # Networking & Security
    'cisco': 'Networking & Security',
    'cisco catalyst': 'Networking & Security',
    'cisco nexus': 'Networking & Security',
    'fortinet': 'Networking & Security',
    'vmware': 'Networking & Security',
    'kerberos': 'Networking & Security',
    'openstack': 'Networking & Security',
    'cloudflare': 'Networking & Security',
    'okta': 'Networking & Security',
    'cyberark': 'Networking & Security',
    'microsoft defender': 'Networking & Security',
    'microsoft intune': 'Networking & Security',
    'hashicorp consul': 'Networking & Security',
    'infoblox': 'Networking & Security',
    'ns1': 'Networking & Security',
    'openssl': 'Networking & Security',
    'owasp': 'Networking & Security',
    'zeromq': 'Networking & Security',
    'sigfox': 'Networking & Security',
    'rss': 'Networking & Security',
    'juniper networks': 'Networking & Security',
    'cogent communications': 'Networking & Security',
    'mobileiron': 'Networking & Security',
    'citrix': 'Networking & Security',
    'boundary': 'Networking & Security',
    'salto': 'Networking & Security',
    
    # Analytics & BI
    'power bi': 'Analytics & BI',
    'qlikview': 'Analytics & BI',
    'looker': 'Analytics & BI',
    'microstrategy': 'Analytics & BI',
    'sas': 'Analytics & BI',
    'numpy': 'Analytics & BI',
    'plotly': 'Analytics & BI',
    'dataiku': 'Analytics & BI',
    'apache spark': 'Analytics & BI',
    'apache flink': 'Analytics & BI',
    'apache kafka': 'Analytics & BI',
    'grafana': 'Analytics & BI',
    'prometheus': 'Analytics & BI',
    'qualtrics': 'Analytics & BI',
    'dynatrace': 'Analytics & BI',
    'icinga': 'Analytics & BI',
    'new relic': 'Analytics & BI',
    'appdynamics': 'Analytics & BI',
    'datasphere': 'Analytics & BI',
    
    # Hardware
    'cognex': 'Hardware',
    'omron': 'Hardware',
    'keyence': 'Hardware',
    'arduino': 'Hardware', 
    'vodafone': 'Hardware',
    'bt': 'Hardware',
    
    # Methodologies
    'scrum': 'Methodologies',  
    'kanban': 'Methodologies',  
    'growth': 'Methodologies',
    'metrics driven': 'Methodologies',
    'uml': 'Methodologies',
    'dx': 'Methodologies',
    'archimate': 'Methodologies',
    
    # Other and Broader Skills
    'call center': 'Other and Broader Skills',
    'dhl': 'Other and Broader Skills',
    'fedex': 'Other and Broader Skills',
    'ups': 'Other and Broader Skills',
    'internship': 'Other and Broader Skills',
    'business development': 'Other and Broader Skills',
    'real estate': 'Other and Broader Skills',
    'contractor': 'Other and Broader Skills',
    'outbound': 'Other and Broader Skills',
    'prospecting': 'Other and Broader Skills',
    'sales prospecting': 'Other and Broader Skills',
    'blockchain': 'Other and Broader Skills',
    'pfs': 'Other and Broader Skills',
    'full time job': 'Other and Broader Skills',
    'swc': 'Other and Broader Skills',
    'walkme': 'Other and Broader Skills',
    'glassdoor': 'Other and Broader Skills',
    'cvs': 'Other and Broader Skills',
    'meister': 'Other and Broader Skills',
    'novi': 'Other and Broader Skills',
    'ativo': 'Other and Broader Skills',
    'como': 'Other and Broader Skills',
    'venda': 'Other and Broader Skills',
    'ams': 'Other and Broader Skills',
    'brt': 'Other and Broader Skills',
    'aos': 'Other and Broader Skills',
    'rms': 'Other and Broader Skills',
    'tricentis': 'Other and Broader Skills',
    'cognigy': 'Other and Broader Skills',
    'genesys': 'Other and Broader Skills',
    'glpi': 'Other and Broader Skills',
    'goanywhere': 'Other and Broader Skills',
    'carta': 'Other and Broader Skills',
    'stripe': 'Other and Broader Skills',
    'recurly': 'Other and Broader Skills',
    'chargebee': 'Other and Broader Skills',
    'recognize': 'Other and Broader Skills',
    'engagez': 'Other and Broader Skills',
    'conveyor': 'Other and Broader Skills',
    'northstar': 'Other and Broader Skills',
    'nextgen': 'Other and Broader Skills',
    'smartrecruiters': 'Other and Broader Skills',
    'workstream': 'Other and Broader Skills',
    'sieben': 'Other and Broader Skills',
    'methode': 'Other and Broader Skills',
    'tandem': 'Other and Broader Skills',
    'support hero': 'Other and Broader Skills',
    'ethereum': 'Other and Broader Skills',
    'atento': 'Other and Broader Skills',
    'agosto': 'Other and Broader Skills',
    'informa': 'Other and Broader Skills',
    'whatsapp': 'Other and Broader Skills',
    'microsoft signalr': 'Other and Broader Skills',
    'jonas': 'Other and Broader Skills'
}






