locations_mapping = {
    'Indiana': 'United States',
    'United States': 'United States',
    'Delaware': 'United States',
    'Romania': 'Romania',
    'India': 'India',
    'Yokohama': 'Japan',
    'Japan': 'Japan',
    'Lincolnton': 'United States',
    'North Carolina': 'United States',
    '28092': 'United States',
    'Hanau': 'Germany',
    'Germany': 'Germany',
    'Campinas': 'Brazil',
    'Brazil': 'Brazil',
    'Charleston': 'United States',
    'South Carolina': 'United States',
    '29418': 'United States',
    'Tennessee': 'United States',
    'Fort Lauderdale': 'United States',
    'Florida': 'United States',
    '33309': 'United States',
    'Singapore': 'Singapore',
    'United Kingdom': 'United Kingdom',
    'France': 'France',
    'Albion': 'United States',
    '46701': 'United States',
    'Madrid': 'Spain',
    'Spain': 'Spain',
    'Bangalore': 'India',
    'Vietnam': 'Vietnam',
    'Malaysia': 'Malaysia',
    'Anderson': 'United States',
    '29621': 'United States',
    'Debrecen': 'Hungary',
    'Hungary': 'Hungary',
    'Pamplona': 'Spain',
    'Bursa': 'Turkey',
    'Turkey': 'Turkey',
    'Salzburg': 'Austria',
    'Austria': 'Austria',
    'Slovenia': 'Slovenia',
    'Vernon Hills': 'United States',
    'Illinois': 'United States',
    '60061': 'United States',
    'London': 'United Kingdom',
    'Tokyo': 'Japan',
    'Australia': 'Australia',
    'Massachusetts': 'United States',
    'Northville': 'United States',
    'Michigan': 'United States',
    'Portugal': 'Portugal',
    'Osnabrück': 'Germany',
    'Berlin': 'Germany',
    'Budapest': 'Hungary',
    'Beijing': 'China',
    'China': 'China',
    'České Budějovice': 'Czechia',
    'Czechia': 'Czechia',
    'Chandler': 'United States',
    'Arizona': 'United States',
    '85226': 'United States',
    'Auburn Hills': 'United States',
    '48326': 'United States',
    'Hartland': 'United States',
    'Wisconsin': 'United States',
    'Vilnius': 'Lithuania',
    'Lithuania': 'Lithuania',
    'Mexico': 'Mexico',
    'Mississippi': 'United States',
    'Shibuya': 'Japan',
    'Dublin': 'Ireland',
    'Ireland': 'Ireland',
    'Shanghai': 'China',
    'Vigo': 'Spain',
    'Houston': 'United States',
    'Texas': 'United States',
    '77061': 'United States',
    'Nebraska': 'United States',
    'Barcelona': 'Spain',
    'Częstochowa': 'Poland',
    'Poland': 'Poland',
    'Mount Prospect': 'United States',
    '60056': 'United States',
    'Sydney': 'Australia',
    'Owatonna': 'United States',
    'Minnesota': 'United States',
    '55060': 'United States',
    'Belgium': 'Belgium',
    'Aveiro': 'Portugal',
    'Leverkusen': 'Germany',
    'Virginia': 'United States',
    'Passau': 'Germany',
    'Bamberg': 'Germany',
    'Bentonville': 'United States',
    'Arkansas': 'United States',
    'South America': 'Colombia',
    'Bogotá': 'Colombia',
    'Colombia': 'Colombia',
    'San Francisco': 'United States',
    'California': 'United States',
    'Georgia': 'United States',
    'Rolla': 'United States',
    'Missouri': 'United States',
    '65401': 'United States',
    'Atlanta': 'United States',
    '30336': 'United States',
    'Charlotte': 'United States',
    '28273': 'United States',
    'Mankato': 'United States',
    '56003': 'United States',
    'Monterrey': 'Mexico',
    'Pune': 'India',
    'Belo Horizonte': 'Brazil',
    'Chile': 'Chile',
    'Bekasi': 'Indonesia',
    'Indonesia': 'Indonesia',
    'Eger': 'Hungary',
    'Mesa': 'United States',
    '85212': 'United States',
    'Burnsville': 'United States',
    'Timișoara': 'Romania',
    'Sunnyvale': 'United States',
    '94085': 'United States',
    'Pančevo': 'Serbia',
    'Serbia': 'Serbia',
    'Plymouth': 'United States',
    '48170': 'United States',
    'Tuscaloosa': 'United States',
    'Alabama': 'United States',
    'Friedrichshafen': 'Germany',
    'Brandenburg': 'Germany',
    'Bethlehem': 'United States',
    'Pennsylvania': 'United States',
    '18017': 'United States',
    'Farmington Hills': 'United States',
    '48331': 'United States',
    'Bucharest': 'Romania',
    'Chennai': 'India',
    'Lafayette': 'United States',
    'Hannover': 'Germany',
    'Villa Park': 'United States',
    '47904': 'United States',
    'Maine': 'United States',
    'Thailand': 'Thailand',
    '60181': 'United States',
    'Niagara': 'United States',
    'New York': 'United States',
    'Fairport': 'United States',
    '14450': 'United States',
    'Denver': 'United States',
    'Colorado': 'United States',
    'Utrecht': 'Netherlands',
    'Netherlands': 'Netherlands',
    'Nederland': 'Netherlands',
    'Chihuahua': 'Mexico',
    'Armenia': 'Armenia',
    'August': 'United States',
    'São Paulo': 'Brazil',
    'Nevada': 'United States',
    'Wartburg': 'United States',
    '37887': 'United States',
    'Ponte de Lima': 'Portugal',
    'Washington': 'United States',
    '48094': 'United States',
    'Buford': 'United States',
    '30518': 'United States',
    'Minneapolis': 'United States',
    'Gothenburg': 'Sweden',
    'Sweden': 'Sweden',
    'Rayong': 'Thailand',
    'Stuttgart': 'Germany',
    'Egypt': 'Egypt',
    'Greece': 'Greece',
    'Koblenz': 'Germany',
    'Ghana': 'Ghana',
    'Hanoi': 'Vietnam',
    'Northern America': 'United States',
    'Europe': 'Germany',
    'Plzeň': 'Czechia',
    'Paris': 'France',
    'Dortmund': 'Germany',
    '55337': 'United States',
    'Chengdu': 'China',
    'Bitterfeld': 'Germany',
    'Neuwied': 'Germany',
    'Canada': 'Canada',
    'Morocco': 'Morocco',
    'Boston': 'United States',
    'Pleasanton': 'United States',
    '94566': 'United States',
    'Guangzhou': 'China',
    'Suzhou': 'China',
    'Marysville': 'United States',
    'Anderlecht': 'Belgium',
    'Stamford': 'United States',
    'Connecticut': 'United States',
    'Saarbrücken': 'Germany',
    'Denmark': 'Denmark',
    'Celaya': 'Mexico',
    'Florence': 'United States',
    'Kentucky': 'United States',
    '41042': 'United States',
    'Istanbul': 'Turkey',
    'Hoffman Estates': 'United States',
    '60192': 'United States',
    'Changsha': 'China',
    'Linz': 'Austria',
    'New Zealand': 'New Zealand',
    'Manisa': 'Turkey',
    'Almaty': 'Kazakhstan',
    'Kazakhstan': 'Kazakhstan',
    'Fountain Inn': 'United States',
    '29644': 'United States',
    'Oak Brook': 'United States',
    'Walnut Ridge': 'United States',
    '72476': 'United States',
    'Louisiana': 'United States',
    'Mexico City': 'Mexico',
    'Pforzheim': 'Germany',
    'Querétaro': 'Mexico',
    'Juárez': 'Mexico',
    'Idaho': 'United States',
    'Livonia': 'United States',
    '48150': 'United States',
    'Ansbach': 'Germany',
    'Watertown': 'United States',
    '02472': 'United States',
    'Eisenach': 'Germany',
    'İzmir': 'Turkey',
    'Braunschweig': 'Germany',
    'Italy': 'Italy',
    'Changzhou': 'China',
    'Atlantic': 'United States',
    'Iowa': 'United States',
    'Wrocław': 'Poland',
    'South Dakota': 'United States',
    'Auckland': 'New Zealand',
    'Grove City': 'United States',
    'Ohio': 'United States',
    '43123': 'United States',
    'Trnava': 'Slovakia',
    'Slovakia': 'Slovakia',
    'Caen': 'France',
    'San Luis Potosí': 'Mexico',
    'South Africa': 'South Africa',
    'Southern Africa': 'South Africa',
    'Ho Chi Minh City': 'Vietnam',
    'Switzerland': 'Switzerland',
    'Garrett': 'United States',
    'Warsaw': 'Poland',
    'Chicago': 'United States',
    'Dresden': 'Germany',
    'Santa Fe': 'United States',
    'Argentina': 'Argentina',
    'Bhāvnagar': 'India',
    'Allentown': 'United States',
    'Saint Joseph': 'United States',
    '49085': 'United States',
    '53029': 'Germany',
    'Tulsa': 'United States',
    'Oklahoma': 'United States',
    'Mechelen': 'Belgium',
    'Amsterdam': 'Netherlands',
    'Düsseldorf': 'Germany',
    'Saitama': 'Japan',
    'Gainesville': 'United States',
    'Eindhoven': 'Netherlands',
    'Petaling Jaya': 'Malaysia',
    'Nottingham': 'United Kingdom',
    'Roseville': 'United States',
    '95747': 'United States',
    'Memphis': 'United States',
    'Shelby': 'United States',
    '28152': 'United States',
    'Manila': 'Philippines',
    'Philippines': 'Philippines',
    'North Charleston': 'United States',
    'Coimbatore': 'India',
    'Ingolstadt': 'Germany',
    'Greenville': 'United States',
    '29645': 'United States',
    'Munster': 'Germany',
    'Braga': 'Portugal',
    'Cartago': 'Costa Rica',
    'Costa Rica': 'Costa Rica',
    'Flowery Branch': 'United States',
    '30542': 'United States',
    'Corpus Christi': 'United States',
    '78406': 'United States',
    'Dayton': 'United States',
    'Aachen': 'Germany',
    'Tampa': 'United States',
    '33607': 'United States',
    'Laredo': 'United States',
    '78045': 'United States',
    '30324': 'United States',
    'Tsuchiura': 'Japan',
    'Braselton': 'United States',
    'Bonn': 'Germany',
    'Lincolnshire': 'United States',
    '60069': 'United States',
    'Austin': 'United States',
    'Philadelphia': 'United States',
    'Rio Bravo': 'Mexico',
    'Brits': 'South Africa',
    'Castelo Branco': 'Portugal',
    'Anna': 'United States',
    'Port Huron': 'United States',
    'Wuhan': 'China',
    'Cali': 'Colombia',
    'Raleigh': 'United States',
    'Heilbronn': 'Germany',
    'Conshohocken': 'United States',
    '19428': 'United States',
    'Jacksonville': 'United States',
    'Kecskemét': 'Hungary',
    'Straubing': 'Germany',
    'Summerville': 'United States',
    '29483': 'United States',
    'Gómez Palacio': 'Mexico',
    'Reutlingen': 'Germany',
    'Toluca': 'Mexico',
    'Nasushiobara': 'Japan',
    'District of Columbia': 'United States',
    'Reynosa': 'Mexico',
    'Klagenfurt': 'Austria',
    'Jiaxing': 'China',
    'Brussels': 'Belgium',
    'Vernon': 'United States',
    'Guadalajara': 'Mexico',
    'Ankara': 'Turkey',
    'Hyderābād': 'India',
    'Jersey City': 'United States',
    'New Jersey': 'United States',
    'Bochum': 'Germany',
    'Bayreuth': 'Germany',
    'Antwerp': 'Belgium',
    'Sofia': 'Bulgaria',
    'Bulgaria': 'Bulgaria',
    'Phoenix': 'United States',
    'Hangzhou': 'China',
    'Socorro': 'United States',
    '79927': 'United States',
    'New Hampshire': 'United States',
    'Pittsburgh': 'United States',
    '15222': 'United States',
    'Decatur': 'United States',
    '62441': 'United States',
    'Sri Lanka': 'Sri Lanka',
    'Montana': 'United States',
    'Detroit': 'United States',
    'Windsor': 'Canada',
    'Novi Sad': 'Serbia',
    'Miami': 'United States',
    'Jamshedpur': 'India',
    'Solihull': 'United Kingdom',
    'Mechanicsville': 'United States',
    '23111': 'United States',
    'Bengaluru': 'India',
    'El Paso': 'United States',
    'Auburn': 'United States',
    'Frankfurt': 'Germany',
    'Campo Grande': 'Brazil',
    '02215': 'United States',
    'Oeiras': 'Portugal',
    'Greer': 'United States',
    '29651': 'United States',
    'Calama': 'Chile',
    'Puteaux': 'France',
    'Gelsenkirchen': 'Germany',
    'Kocaeli': 'Turkey',
    '48040': 'United States',
    'Schweinfurt': 'Germany',
    'Sakarya': 'Turkey',
    'Innsbruck': 'Austria',
    'Sumaré': 'Brazil',
    'Seattle': 'United States',
    'Cluj-Napoca': 'Romania',
    'Qingdao': 'China',
    '48073': 'United States',
    'Asia': 'China',
    'Panama': 'Panama',
    'Grand Rapids': 'United States',
    '49512': 'United States',
    'Bourges': 'France',
    'Brno': 'Czechia',
    'Czech Republic': 'Czechia',
    'Saint Paul': 'United States',
    '55127': 'United States',
    'Zürich': 'Switzerland',
    'Duncan': 'United States',
    'Baltimore': 'United States',
    'Maryland': 'United States',
    'CA': 'United States',
    'Craiova': 'Romania',
    'Burlington': 'United States',
    '95678': 'United States',
    'High Point': 'United States',
    '27263': 'United States',
    'Welcome': 'United States',
    'Setúbal': 'Portugal',
    'Wetzlar': 'Germany',
    'Bern': 'Switzerland',
    'Dornbirn': 'Austria',
    'Salamanca': 'Spain',
    'Vienna': 'Austria',
    'Faro': 'Portugal',
    'Ambato': 'Ecuador',
    'Ecuador': 'Ecuador',
    'Lancaster': 'United States',
    'Chongqing': 'China',
    'Ramos Arizpe': 'Mexico',
    'Santa Barbara': 'United States',
    'Munich': 'Germany',
    'Bologna': 'Italy',
    'Finland': 'Finland',
    'Zwolle': 'Netherlands',
    'Milan': 'Italy',
    'Oregon': 'United States',
    'Tlaquepaque': 'Mexico',
    'Magdeburg': 'Germany',
    'Immenstadt': 'Germany',
    'Hebron': 'United States',
    '41048': 'United States',
    'Chad': 'Chad',
    'Czech': 'Czechia',
    'Lisbon': 'Portugal',
    'Hawaii': 'United States',
    'Gliwice': 'Poland',
    'Ravensburg': 'Germany',
    'Augsburg': 'Germany',
    'Sibiu': 'Romania',
    'Dubai': 'United Arab Emirates',
    'United Arab Emirates': 'United Arab Emirates',
    '11433': 'United States',
    'Salt Lake City': 'United States',
    'Utah': 'United States',
    'Allen Park': 'United States',
    '48101': 'United States',
    'San Antonio': 'United States',
    'Santa Fe Springs': 'United States',
    'Athens': 'Greece',
    '90670': 'United States',
    'Fridley': 'United States',
    '55421': 'United States',
    'San': 'United States',
    'Mali': 'Mali',
    'Kalamazoo': 'United States',
    '49009': 'United States',
    'Amiens': 'France',
    'Antofagasta': 'Chile',
    'Edmonton': 'Canada',
    'Alberta': 'Canada',
    'Bandung': 'Indonesia',
    'Kranj': 'Slovenia',
    'Morrisville': 'United States',
    '19067': 'United States',
    'Gaithersburg': 'United States',
    '20878': 'United States',
    'Weihai': 'China',
    'Jaipur': 'India',
    '30501': 'United States',
    'Brasília': 'Brazil',
    '17601': 'United States',
    'Los Angeles': 'United States',
    'San Diego': 'United States',
    'Rājkot': 'India',
    'Jamaica': 'Jamaica',
    '11430': 'United States',
    'Lincoln': 'United States',
    '68507': 'United States',
    'LA': 'United States',
    'Dallas': 'United States',
    'Vermont': 'United States',
    'Peru': 'Peru',
    '46970': 'United States',
    'Prague': 'Czechia',
    'Fenton': 'United States',
    '48430': 'United States',
    'Porto': 'Portugal',
    'Londonderry': 'United States',
    '03053': 'United States',
    'Hamamatsu': 'Japan',
    'Miramar': 'United States',
    'Bāli': 'India',
    'Mooresville': 'United States',
    '28117': 'United States',
    '18020': 'United States',
    'Vernier': 'Switzerland',
    'Turin': 'Italy',
    'Wilmington': 'United States',
    '28405': 'United States',
    'Busan': 'South Korea',
    'South Korea': 'South Korea',
    'Graz': 'Austria',
    '35401': 'United States',
    'Aschaffenburg': 'Germany',
    'Zaria': 'Nigeria',
    'Nigeria': 'Nigeria',
    'São Bernardo do Campo': 'Brazil',
    'Shah Alam': 'Malaysia',
    'Trujillo': 'Peru',
    'Leipzig': 'Germany',
    'Unity': 'United States',
    'Belgrade': 'Serbia',
    'Portland': 'United States',
    'Hagen': 'Germany',
    'Alicante': 'Spain',
    'Viseu': 'Portugal',
    'Toyota': 'Japan',
    'Bielefeld': 'Germany',
    'Wuxi': 'China',
    'Alexandria': 'Egypt',
    'Wilde': 'Argentina',
    'Orlando': 'United States',
    'Lille': 'France',
    'Sacramento': 'United States',
    'Arras': 'France',
    'Mut': 'Turkey',
    '48836': 'United States',
    'Vila Real': 'Portugal',
    'Accra': 'Ghana',
    'Southampton': 'United States',
    '18966': 'United States',
    'Kaunas': 'Lithuania',
    'Bordeaux': 'France',
    'Gießen': 'Germany',
    'Bratislava': 'Slovakia',
    'North America': 'United States',
    'Tochigi': 'Japan'
}