keywords_skills_mapping = {
    # Programming Languages
    'c++': 'Programming Languages',
    'python': 'Programming Languages',
    'c#': 'Programming Languages',
    'java': 'Programming Languages',
    'kotlin': 'Programming Languages',
    'javascript': 'Programming Languages',
    'php': 'Programming Languages',
    'ruby': 'Programming Languages',
    'abap': 'Programming Languages',
    'go': 'Programming Languages',
    'typescript': 'Programming Languages',
    'perl': 'Programming Languages',
    'dart': 'Programming Languages',
    'c': 'Programming Languages',
    'cobol': 'Programming Languages',
    'objective-c': 'Programming Languages',
    'scala': 'Programming Languages',
    'solidity': 'Programming Languages',
    'visual basic .net': 'Programming Languages',  # visual basic .net
    
    # Frameworks & Libraries
    '.net': 'Frameworks & Libraries',
    'angular': 'Frameworks & Libraries',
    'django': 'Frameworks & Libraries',
    'node.js': 'Frameworks & Libraries',
    'angularjs': 'Frameworks & Libraries',
    'react': 'Frameworks & Libraries',
    'spring framework': 'Frameworks & Libraries',
    'spring boot': 'Frameworks & Libraries',
    'flask': 'Frameworks & Libraries',
    'jquery': 'Frameworks & Libraries',
    'vue.js': 'Frameworks & Libraries',
    'laravel': 'Frameworks & Libraries',
    'gatsby': 'Frameworks & Libraries',
    'graphql': 'Frameworks & Libraries',
    'remix': 'Frameworks & Libraries',
    'primefaces': 'Frameworks & Libraries',
    'blazor': 'Frameworks & Libraries',
    'rxjs': 'Frameworks & Libraries',
    'svelte': 'Frameworks & Libraries',
    'drupal': 'Frameworks & Libraries',
    'jekyll': 'Frameworks & Libraries',
    'bootstrap': 'Frameworks & Libraries',
    'ext js': 'Frameworks & Libraries',
    'next.js': 'Frameworks & Libraries',
    'mui': 'Frameworks & Libraries',
    'primeng': 'Frameworks & Libraries',
    'scikit-learn': 'Frameworks & Libraries',
    'pytorch': 'Frameworks & Libraries',
    'tensorflow': 'Frameworks & Libraries',
    'ionic': 'Frameworks & Libraries',
    'j2ee': 'Frameworks & Libraries',
    'junit': 'Frameworks & Libraries',
    'nunit': 'Frameworks & Libraries',
    'redux': 'Frameworks & Libraries',
    'nette framework': 'Frameworks & Libraries',
    'express': 'Frameworks & Libraries',  # node.js ecosystem
    
    # Tools & Platforms
    'github': 'Tools & Platforms',
    'gitlab': 'Tools & Platforms',
    'jenkins': 'Tools & Platforms',
    'docker': 'Tools & Platforms',
    'kubernetes': 'Tools & Platforms',
    'ansible': 'Tools & Platforms',
    'postman': 'Tools & Platforms',
    'selenium': 'Tools & Platforms',
    'appium': 'Tools & Platforms',
    'gradle': 'Tools & Platforms',
    'gerrit': 'Tools & Platforms',
    'ranorex': 'Tools & Platforms',
    'splunk': 'Tools & Platforms',
    'matlab': 'Tools & Platforms',
    'minitab': 'Tools & Platforms',
    'autocad': 'Tools & Platforms',
    'arduino': 'Tools & Platforms',
    'stata': 'Tools & Platforms',
    'labview': 'Tools & Platforms',
    'simulink': 'Tools & Platforms',
    'ansys': 'Tools & Platforms',
    'catia': 'Tools & Platforms',
    'ptc creo': 'Tools & Platforms',
    'android studio': 'Tools & Platforms',
    'visual studio code': 'Tools & Platforms',
    'eclipse ide': 'Tools & Platforms',
    'microsoft visual studio': 'Tools & Platforms',
    'autodesk eagle': 'Tools & Platforms',
    'autodesk revit': 'Tools & Platforms',
    'corel': 'Tools & Platforms',
    'dreamweaver': 'Tools & Platforms',
    'paintshop pro': 'Tools & Platforms',
    'sourcetree': 'Tools & Platforms',
    'webstorm': 'Tools & Platforms',
    'robot framework': 'Tools & Platforms',
    
    # Cloud Services
    'microsoft azure': 'Cloud Services',
    'azure devops': 'Cloud Services',
    'google cloud': 'Cloud Services',
    'amazon web services': 'Cloud Services',
    'google cloud platform': 'Cloud Services',
    'oracle cloud': 'Cloud Services',
    'azure stream analytics': 'Cloud Services',
    'azure kubernetes service': 'Cloud Services',
    'azure pipelines': 'Cloud Services',
    'azure synapse analytics': 'Cloud Services',
    'azure sql': 'Cloud Services',
    'azure artifacts': 'Cloud Services',
    'azure boards': 'Cloud Services',
    'azure monitor': 'Cloud Services',
    'google kubernetes engine': 'Cloud Services',
    'aws iot': 'Cloud Services',
    'aws lambda': 'Cloud Services',
    'amazon ecs': 'Cloud Services',
    'amazon rds': 'Cloud Services',
    'google workspace': 'Cloud Services',
    'heroku': 'Cloud Services',  # implied by "heroku" in list
    
    # Databases
    'mysql': 'Databases',
    'mongodb': 'Databases',
    'postgresql': 'Databases',
    'oracle database': 'Databases',
    'microsoft sql server': 'Databases',
    'nosql': 'Databases',
    'sqlite': 'Databases',
    'couchbase': 'Databases',
    'redis': 'Databases',
    'netezza': 'Databases',
    'teradata analytics platform': 'Databases',
    'sybase': 'Databases',
    'mariadb': 'Databases',
    
    # Operating Systems
    'linux': 'Operating Systems',
    'windows server': 'Operating Systems',
    'macos': 'Operating Systems',
    'ubuntu': 'Operating Systems',
    'ibm aix': 'Operating Systems',
    'debian': 'Operating Systems',
    'unix': 'Operating Systems',
    'windows 11': 'Operating Systems',
    'suse': 'Operating Systems',
    'vmware esxi': 'Operating Systems',
    
    # DevOps & CI/CD
    'devops': 'DevOps & CI/CD',  # implied context
    'continuous deployment': 'DevOps & CI/CD',
    'git': 'DevOps & CI/CD',
    'gitlab ci': 'DevOps & CI/CD',
    'circleci': 'DevOps & CI/CD',
    'jenkins': 'DevOps & CI/CD',  # repeated for context
    'docker': 'DevOps & CI/CD',  # repeated for context
    'kubernetes': 'DevOps & CI/CD',  # repeated for context
    'ansible': 'DevOps & CI/CD',  # repeated for context
    'gradle': 'DevOps & CI/CD',  # repeated for context
    'terraform': 'DevOps & CI/CD',  # implied by hashicorp products
    
    # ERP & Business Software
    'sap': 'ERP & Business Software',
    'sap successfactors': 'ERP & Business Software',
    'sap s/4hana': 'ERP & Business Software',
    'sap hana': 'ERP & Business Software',
    'sap erp': 'ERP & Business Software',
    'sap abap': 'ERP & Business Software',
    'sap financial accounting': 'ERP & Business Software',
    'sap sales': 'ERP & Business Software',
    'sap controlling': 'ERP & Business Software',
    'sap fiori': 'ERP & Business Software',
    'sap crm': 'ERP & Business Software',
    'sap analytics cloud': 'ERP & Business Software',
    'sap bw/4hana': 'ERP & Business Software',
    'sap netweaver': 'ERP & Business Software',
    'sap strategic enterprise management': 'ERP & Business Software',
    'sap materials management': 'ERP & Business Software',
    'sap treasury and risk management': 'ERP & Business Software',
    'sap quality management': 'ERP & Business Software',
    'sap solution manager': 'ERP & Business Software',
    'sap lumira': 'ERP & Business Software',
    'sap data migration': 'ERP & Business Software',
    'sap master data governance': 'ERP & Business Software',
    'sap cloud platform': 'ERP & Business Software',
    'sap grc': 'ERP & Business Software',
    'sap enable now': 'ERP & Business Software',
    'sap business warehouse': 'ERP & Business Software',
    'sap warehouse management': 'ERP & Business Software',
    'sap sales and distribution': 'ERP & Business Software',
    'sap ariba': 'ERP & Business Software',
    'sap hybris': 'ERP & Business Software',
    'oracle': 'ERP & Business Software',
    'netsuite': 'ERP & Business Software',
    'microsoft dynamics': 'ERP & Business Software',
    'microsoft dynamics 365': 'ERP & Business Software',
    'microsoft dynamics crm': 'ERP & Business Software',
    'workday payroll': 'ERP & Business Software',
    'adp': 'ERP & Business Software',
    'ukg': 'ERP & Business Software',
    'kronos': 'ERP & Business Software',
    'coupa': 'ERP & Business Software',
    'celonis': 'ERP & Business Software',
    'alteryx': 'ERP & Business Software',
    'talend': 'ERP & Business Software',
    'informatica': 'ERP & Business Software',
    
    # CRM
    'salesforce': 'CRM',
    'salesforce commerce cloud': 'CRM',
    'salesforce marketing cloud': 'CRM',
    'hubspot': 'CRM',
    'zendesk': 'CRM',  # implied context
    'gainsight': 'CRM',
    'freshdesk': 'CRM',  # implied context
    
    # CMS & Web Platforms
    'wordpress': 'CMS & Web Platforms',
    'drupal': 'CMS & Web Platforms',
    'sitecore': 'CMS & Web Platforms',
    'contentful': 'CMS & Web Platforms',
    'contentstack': 'CMS & Web Platforms',
    'shopify': 'CMS & Web Platforms',
    'magento': 'CMS & Web Platforms',  # e-commerce implied
    'webflow': 'CMS & Web Platforms',
    
    # Marketing & Social Media Tools
    'google analytics': 'Marketing & Social Media Tools',
    'google ads': 'Marketing & Social Media Tools',
    'google adwords': 'Marketing & Social Media Tools',
    'facebook ads': 'Marketing & Social Media Tools',
    'linkedin': 'Marketing & Social Media Tools',
    'instagram': 'Marketing & Social Media Tools',  # implied by social media
    'agorapulse': 'Marketing & Social Media Tools',
    'hootsuite': 'Marketing & Social Media Tools',
    'semrush': 'Marketing & Social Media Tools',
    'ahrefs': 'Marketing & Social Media Tools',
    'marketo': 'Marketing & Social Media Tools',
    'hubspot': 'Marketing & Social Media Tools',  # repeated for context
    'pinterest': 'Marketing & Social Media Tools',
    'youtube': 'Marketing & Social Media Tools',
    'optimizely': 'Marketing & Social Media Tools',
    'google optimize': 'Marketing & Social Media Tools',
    'google my business': 'Marketing & Social Media Tools',
    'linkedin sales navigator': 'Marketing & Social Media Tools',
    'zoominfo': 'Marketing & Social Media Tools',
    'outreach.io': 'Marketing & Social Media Tools',
    'demandbase': 'Marketing & Social Media Tools',
    'sendoso': 'Marketing & Social Media Tools',
    'account based marketing': 'Marketing & Social Media Tools',
    'demand generation': 'Marketing & Social Media Tools',
    'content marketing': 'Marketing & Social Media Tools',
    'seo': 'Marketing & Social Media Tools',
    
    # Design Tools
    'figma': 'Design Tools',
    'adobe creative suite': 'Design Tools',
    'adobe photoshop': 'Design Tools',
    'adobe indesign': 'Design Tools',
    'adobe illustrator': 'Design Tools',
    'adobe xd': 'Design Tools',
    'adobe after effects': 'Design Tools',
    'adobe acrobat dc': 'Design Tools',
    'adobe premiere pro': 'Design Tools',
    'adobe captivate': 'Design Tools',
    'adobe framemaker': 'Design Tools',
    'canva': 'Design Tools',
    'sketch': 'Design Tools',  # implied context
    
    # Project Management
    'jira': 'Project Management',
    'trello': 'Project Management',
    'asana': 'Project Management',
    'monday.com': 'Project Management',  # implied context
    'smartsheet': 'Project Management',
    'microsoft teams': 'Project Management',
    'microsoft planner': 'Project Management',  # implied by office suite
    'clickup': 'Project Management',  # implied context
    'conceptboard': 'Project Management',
    'cutover': 'Project Management',
    'kanban': 'Project Management',
    'scrum': 'Project Management',
    
    # Networking & Security
    'cisco': 'Networking & Security',
    'cisco catalyst': 'Networking & Security',
    'cisco nexus': 'Networking & Security',
    'fortinet': 'Networking & Security',
    'palo alto': 'Networking & Security',  # implied context
    'vmware': 'Networking & Security',
    'kerberos': 'Networking & Security',
    'openstack': 'Networking & Security',
    'cloudflare': 'Networking & Security',
    'okta': 'Networking & Security',
    'cyberark': 'Networking & Security',
    'microsoft defender': 'Networking & Security',
    'microsoft intune': 'Networking & Security',
    'hashicorp consul': 'Networking & Security',
    'infoblox': 'Networking & Security',
    'ns1': 'Networking & Security',
    'openssl': 'Networking & Security',
    'owasp': 'Networking & Security',
    'zeromq': 'Networking & Security',
    
    # Analytics & BI
    'power bi': 'Analytics & BI',
    'tableau': 'Analytics & BI',  # implied context
    'qlikview': 'Analytics & BI',
    'looker': 'Analytics & BI',
    'microstrategy': 'Analytics & BI',
    'sas': 'Analytics & BI',
    'numpy': 'Analytics & BI',
    'pandas': 'Analytics & BI',  # implied by Python ecosystem
    'plotly': 'Analytics & BI',
    'dataiku': 'Analytics & BI',
    'apache spark': 'Analytics & BI',
    'apache flink': 'Analytics & BI',
    'apache kafka': 'Analytics & BI',
    'grafana': 'Analytics & BI',
    'prometheus': 'Analytics & BI',
    'qualtrics': 'Analytics & BI',
    'qualaroo': 'Analytics & BI',  # implied context
    
    # Hardware
    'cognex': 'Hardware',
    'omron': 'Hardware',
    'keyence': 'Hardware',
    'arduino': 'Hardware',  # repeated for context
    'raspberry pi': 'Hardware',  # implied context
    
    # Methodologies
    'agile': 'Methodologies',  # implied context
    'scrum': 'Methodologies',  # repeated for context
    'kanban': 'Methodologies',  # repeated for context
    'growth': 'Methodologies',
    'metrics driven': 'Methodologies',
    
    # Other
    'call center': 'Other',
    'hris': 'Other',
    'social media': 'Other',
    'customer success': 'Other',
    'internship': 'Other',
    'ecommerce': 'Other',
    'e-commerce': 'Other',
    'business development': 'Other',
    'real estate': 'Other',
    'contractor': 'Other',
    'branding': 'Other',
    'outbound': 'Other',
    'marketing campaigns': 'Other',
    'front-end': 'Other',
    'back-end': 'Other',
    'ui/ux': 'Other',
    'bem': 'Other',
    'prospecting': 'Other',
    'sales prospecting': 'Other',
    'copywriter': 'Other',
    'martech': 'Other',
    'blockchain': 'Other',
    'pfs': 'Other',
    'uml': 'Other',
    'json': 'Other',
    'websocket': 'Other',
    'sigfox': 'Other',
    'xml': 'Other',  # implied context
    'rss': 'Other',
    'dx': 'Other',
    'full time job': 'Other',
    'cropping': 'Other',
    'post-production': 'Other',
    'timesheets': 'Other',
    'metadata': 'Other',
    'swc': 'Other',
    'vite': 'Other',
    'xslt': 'Other',
    'cuda': 'Other',
    'webrtc': 'Other',
    'jwt': 'Other',  # implied security context
    'openid connect': 'Other',
    'grpc': 'Other',
    'rest api': 'Other',  # implied context
    'soap': 'Other',  # implied context
    'rabbitmq': 'Other',
    'apache tomcat': 'Other',
    'apache jmeter': 'Other',
    'apache airflow': 'Other',
    'apache hadoop': 'Other',
    'lucene': 'Other',
    'solr': 'Other',
    'elasticsearch': 'Other',
    'opensearch': 'Other',
    'mlflow': 'Other',
    'dbt': 'Other',
    'fivetran': 'Other',
    'walkme': 'Other',
    'jupyter': 'Other',
    'r': 'Other',  # implied analytics context
    'cloudera': 'Other',
    'databricks': 'Other',
    'azure databricks': 'Other',
    'snowflake': 'Other',
    'hadoop': 'Other',
    'kafka': 'Other',  # implied context
    'nifi': 'Other',  # implied context
    'airflow': 'Other',  # implied context
    'atlassian': 'Other',
    'atlassian jira': 'Other',
    'atlassian bitbucket': 'Other',
    'concur': 'Other',
    'servicenow': 'Other',
    'bmc remedy': 'Other',
    'microsoft excel': 'Other',
    'microsoft word': 'Other',
    'microsoft powerpoint': 'Other',
    'microsoft outlook': 'Other',
    'microsoft 365': 'Other',
    'office 365': 'Other',
    'microsoft power bi': 'Other',
    'microsoft power apps': 'Other',
    'microsoft power automate': 'Other',
    'microsoft sharepoint': 'Other',
    'microsoft sharepoint online': 'Other',
    'microsoft active directory': 'Other',
    'microsoft system center': 'Other',
    'microsoft advertising': 'Other',
    'microsoft signalr': 'Other',
    'microsoft.net': 'Other',
    'google sheets': 'Other',
    'google drive': 'Other',
    'zoom': 'Other',
    'skype': 'Other',
    'teams': 'Other',  # implied context
    'slack': 'Other',  # implied context
    'whatsapp': 'Other',
    'telegram': 'Other',  # implied context
    'glassdoor': 'Other',
    'indeed': 'Other',  # implied context
    'gmail': 'Other',  # implied context
    'outlook': 'Other',  # implied context
    'cvs': 'Other',
    'svn': 'Other',  # implied version control
    'mercurial': 'Other',  # implied version control
    'perforce': 'Other',  # implied version control
    'windchill': 'Other',
    'centro': 'Other',
    'meister': 'Other',
    'novi': 'Other',
    'ativo': 'Other',
    'como': 'Other',
    'venda': 'Other',
    'ams': 'Other',
    'brt': 'Other',
    'aos': 'Other',
    'rms': 'Other',
    'iis': 'Other',
    'nginx': 'Other',
    'jboss': 'Other',
    'wildfly': 'Other',  # implied context
    'tomcat': 'Other',  # implied context
    'webmethods': 'Other',
    'outsystems': 'Other',
    'axure': 'Other',
    'unity3d': 'Other',
    'pwa': 'Other',
    'jda': 'Other',
    'blue yonder': 'Other',
    'kinaxis': 'Other',
    'personio': 'Other',
    'swimlane': 'Other',
    'tricentis': 'Other',
    'cognigy': 'Other',
    'genesys': 'Other',
    'twilio': 'Other',  # implied context
    'dhl': 'Other',
    'fedex': 'Other',
    'ups': 'Other',
    'vodafone': 'Other',
    'bt': 'Other',
    'juniper networks': 'Other',
    'thingworx': 'Other',
    'oracle enterprise manager': 'Other',
    'glpi': 'Other',
    'goanywhere': 'Other',
    'carta': 'Other',
    'mobx': 'Other',
    'archimate': 'Other',
    'stripe': 'Other',
    'recurly': 'Other',
    'chargebee': 'Other',
    'netcore': 'Other',
    'quickbooks': 'Other',
    'xero': 'Other',  # implied context
    'hyperion': 'Other',
    'recognize': 'Other',
    'engagez': 'Other',
    'borlabs cookie': 'Other',
    'leadfeeder': 'Other',
    'bizzabo': 'Other',
    'hopin': 'Other',
    'provenexpert': 'Other',
    'salsify': 'Other',
    'boundary': 'Other',
    'kahoot': 'Other',
    'jonas': 'Other',
    'dynatrace': 'Other',
    'conveyor': 'Other',
    'demandware': 'Other',
    'vue storefront': 'Other',
    'northstar': 'Other',
    'blackline': 'Other',
    'churnzero': 'Other',
    'planhat': 'Other',
    'salto': 'Other',
    'nextgen': 'Other',
    'artifactory': 'Other',
    'sonarqube': 'Other',
    'icinga': 'Other',
    'new relic': 'Other',
    'appdynamics': 'Other',
    'smartrecruiters': 'Other',
    'workstream': 'Other',
    'edenred': 'Other',
    'articulate 360': 'Other',
    'covisint': 'Other',
    'hydrogen': 'Other',
    'jetpack': 'Other',
    'outreach': 'Other',
    'fivetran': 'Other',  # repeated for context
    'sieben': 'Other',
    'buildout': 'Other',
    'wonderlic': 'Other',
    'methode': 'Other',
    'tandem': 'Other',
    'datasphere': 'Other',
    'weights & biases': 'Other',
    'zuora': 'Other',
    'cogent communications': 'Other',
    'mobileiron': 'Other',
    '1password': 'Other',
    'insightsquared': 'Other',
    'avid pro tools': 'Other',
    'boomi': 'Other',
    'mulesoft anypoint platform': 'Other',
    'dataweave': 'Other',
    'oracle exadata': 'Other',
    'centricity': 'Other',
    'support hero': 'Other',
    'keyless': 'Other',
    'automic': 'Other',
    'ethereum': 'Other',
    'ethers': 'Other',
    'citrix': 'Other',
    'planisware': 'Other',
    'commercetools': 'Other',
    'atento': 'Other',
    'agosto': 'Other',
    'informa': 'Other',
    'centro': 'Other'  # repeated for consistency
}